# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2656d9f4e2514bbfda89e756c2635d3ba2b3c75753699aa50fc9c04eaf5f41dd187f8fe86489381ad365cf61c1d806211fac6148b060bd910a202e2455e5bd1

test:
  secret_key_base: b4dac92d816969641960e8491466559a3b3a28658453b1c9e94f4a0482a92d77f850e395534fccb3520639075ccce75469102a3b7cd765ab6bc2f68e8908fa03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
